export interface PackageTier {
  id: string
  name: string
  followers: number
  price: number
  originalPrice: number
  currency: string
  delivery: string
  tier: "basic" | "pro" | "vip"
  popular: boolean
  bestValue: boolean
  emoji: string
  engagementPercent: number
  guaranteeDays: number
  benefits: string[]
  japServiceId?: string // ID of the service in JAP
}

export const instagramFollowersPackages: PackageTier[] = [
  {
    id: "starter",
    name: "STARTER",
    followers: 2000,
    price: 14.99,
    originalPrice: 29.98,
    currency: "USD",
    delivery: "24-48h",
    tier: "basic",
    popular: false,
    bestValue: false,
    emoji: "🚀",
    engagementPercent: 5,
    guaranteeDays: 15,
    benefits: ["realFollowers", "gradualDelivery", "emailSupport"],
    japServiceId: "1",
  },
  {
    id: "growth",
    name: "GROWTH",
    followers: 5000,
    price: 29.99,
    originalPrice: 59.98,
    currency: "USD",
    delivery: "24-48h",
    tier: "basic",
    popular: true,
    bestValue: false,
    emoji: "🤩",
    engagementPercent: 10,
    guaranteeDays: 30,
    benefits: ["realFollowers", "gradualDelivery", "prioritySupport"],
    japServiceId: "3",
  },
  {
    id: "viral",
    name: "VIRAL",
    followers: 10000,
    price: 49.99,
    originalPrice: 99.98,
    currency: "USD",
    delivery: "48-72h",
    tier: "pro",
    popular: false,
    bestValue: true,
    emoji: "😎",
    engagementPercent: 15,
    guaranteeDays: 60,
    benefits: ["premiumFollowers", "gradualDelivery", "prioritySupport", "freeGuide"],
    japServiceId: "4",
  },
  {
    id: "influencer",
    name: "INFLUENCER",
    followers: 20000,
    price: 89.99,
    originalPrice: 179.98,
    currency: "USD",
    delivery: "3-5 días",
    tier: "pro",
    popular: false,
    bestValue: false,
    emoji: "🤑",
    engagementPercent: 20,
    guaranteeDays: 90,
    benefits: ["eliteFollowers", "gradualDelivery", "dedicatedSupport", "freeGuide", "accountProtection"],
    japServiceId: "5",
  },
  {
    id: "celebrity",
    name: "CELEBRITY",
    followers: 50000,
    price: 199.99,
    originalPrice: 399.98,
    currency: "USD",
    delivery: "5-7 días",
    tier: "vip",
    popular: false,
    bestValue: false,
    emoji: "👑",
    engagementPercent: 25,
    guaranteeDays: 180,
    benefits: [
      "vipFollowers",
      "gradualDelivery",
      "vipSupport",
      "freeGuide",
      "accountProtection",
      "aiStrategy",
      "exploreBoost",
      "exclusivePerks",
    ],
    japServiceId: "6",
  },
]

export const tiktokFollowersPackages: PackageTier[] = [
  {
    id: "starter",
    name: "STARTER",
    followers: 1000,
    price: 7.99,
    originalPrice: 15.98,
    currency: "USD",
    delivery: "24-48h",
    tier: "basic",
    popular: false,
    bestValue: false,
    emoji: "🚀",
    engagementPercent: 5,
    guaranteeDays: 15,
    benefits: ["realFollowers", "gradualDelivery", "emailSupport"],
    japServiceId: "201",
  },
  {
    id: "growth",
    name: "GROWTH",
    followers: 2500,
    price: 17.99,
    originalPrice: 35.98,
    currency: "USD",
    delivery: "24-48h",
    tier: "basic",
    popular: true,
    bestValue: false,
    emoji: "🤩",
    engagementPercent: 10,
    guaranteeDays: 30,
    benefits: ["realFollowers", "gradualDelivery", "prioritySupport"],
    japServiceId: "202",
  },
  {
    id: "viral",
    name: "VIRAL",
    followers: 5000,
    price: 34.99,
    originalPrice: 69.98,
    currency: "USD",
    delivery: "48-72h",
    tier: "pro",
    popular: false,
    bestValue: true,
    emoji: "😎",
    engagementPercent: 15,
    guaranteeDays: 60,
    benefits: ["premiumFollowers", "gradualDelivery", "prioritySupport", "freeGuide"],
    japServiceId: "203",
  },
  {
    id: "influencer",
    name: "INFLUENCER",
    followers: 10000,
    price: 59.99,
    originalPrice: 119.98,
    currency: "USD",
    delivery: "3-5 días",
    tier: "pro",
    popular: false,
    bestValue: false,
    emoji: "🤑",
    engagementPercent: 20,
    guaranteeDays: 90,
    benefits: ["eliteFollowers", "gradualDelivery", "dedicatedSupport", "freeGuide", "accountProtection"],
    japServiceId: "204",
  },
  {
    id: "celebrity",
    name: "CELEBRITY",
    followers: 25000,
    price: 129.99,
    originalPrice: 259.98,
    currency: "USD",
    delivery: "5-7 días",
    tier: "vip",
    popular: false,
    bestValue: false,
    emoji: "👑",
    engagementPercent: 25,
    guaranteeDays: 180,
    benefits: [
      "vipFollowers",
      "gradualDelivery",
      "vipSupport",
      "freeGuide",
      "accountProtection",
      "aiStrategy",
      "fypBoost",
      "exclusivePerks",
    ],
    japServiceId: "205",
  },
]

export const youtubeSubscribersPackages: PackageTier[] = [
  {
    id: "starter",
    name: "STARTER",
    followers: 500,
    price: 14.99,
    originalPrice: 29.98,
    currency: "USD",
    delivery: "24-48h",
    tier: "basic",
    popular: false,
    bestValue: false,
    emoji: "🚀",
    engagementPercent: 5,
    guaranteeDays: 15,
    benefits: ["realFollowers", "gradualDelivery", "emailSupport"],
    japServiceId: "301",
  },
  {
    id: "growth",
    name: "GROWTH",
    followers: 1000,
    price: 24.99,
    originalPrice: 49.98,
    currency: "USD",
    delivery: "24-48h",
    tier: "basic",
    popular: true,
    bestValue: false,
    emoji: "🤩",
    engagementPercent: 10,
    guaranteeDays: 30,
    benefits: ["realFollowers", "gradualDelivery", "prioritySupport"],
    japServiceId: "302",
  },
  {
    id: "viral",
    name: "VIRAL",
    followers: 2500,
    price: 54.99,
    originalPrice: 109.98,
    currency: "USD",
    delivery: "48-72h",
    tier: "pro",
    popular: false,
    bestValue: true,
    emoji: "😎",
    engagementPercent: 15,
    guaranteeDays: 60,
    benefits: ["premiumFollowers", "gradualDelivery", "prioritySupport", "freeGuide"],
    japServiceId: "303",
  },
  {
    id: "influencer",
    name: "INFLUENCER",
    followers: 5000,
    price: 99.99,
    originalPrice: 199.98,
    currency: "USD",
    delivery: "3-5 días",
    tier: "pro",
    popular: false,
    bestValue: false,
    emoji: "🤑",
    engagementPercent: 20,
    guaranteeDays: 90,
    benefits: [
      "eliteFollowers",
      "gradualDelivery",
      "dedicatedSupport",
      "freeGuide",
      "accountProtection",
      "watchTimeBoost",
    ],
    japServiceId: "304",
  },
  {
    id: "celebrity",
    name: "CELEBRITY",
    followers: 10000,
    price: 179.99,
    originalPrice: 359.98,
    currency: "USD",
    delivery: "5-7 días",
    tier: "vip",
    popular: false,
    bestValue: false,
    emoji: "👑",
    engagementPercent: 25,
    guaranteeDays: 180,
    benefits: [
      "vipFollowers",
      "gradualDelivery",
      "vipSupport",
      "freeGuide",
      "accountProtection",
      "watchTimeBoost",
      "aiStrategy",
      "monetizationHelp",
      "exclusivePerks",
    ],
    japServiceId: "305",
  },
]

export const allServices = {
  instagram: {
    followers: instagramFollowersPackages,
    likes: [
      { id: "likes-1000", amount: 1000, price: 4.99, originalPrice: 9.98, japServiceId: "2" },
      { id: "likes-2000", amount: 2000, price: 8.99, originalPrice: 17.98, japServiceId: "7" },
      { id: "likes-5000", amount: 5000, price: 17.99, originalPrice: 35.98, japServiceId: "8" },
      { id: "likes-10000", amount: 10000, price: 29.99, originalPrice: 59.98, japServiceId: "9" },
      { id: "likes-20000", amount: 20000, price: 49.99, originalPrice: 99.98, japServiceId: "10" },
    ],
    views: [
      { id: "views-2000", amount: 2000, price: 2.99, originalPrice: 5.98, japServiceId: "11" },
      { id: "views-10000", amount: 10000, price: 7.99, originalPrice: 15.98, japServiceId: "12" },
      { id: "views-20000", amount: 20000, price: 12.99, originalPrice: 25.98, japServiceId: "13" },
      { id: "views-100000", amount: 100000, price: 34.99, originalPrice: 69.98, japServiceId: "14" },
      { id: "views-200000", amount: 200000, price: 59.99, originalPrice: 119.98, japServiceId: "15" },
    ],
    comments: [
      { id: "comments-10", amount: 10, price: 4.99, originalPrice: 9.98 },
      { id: "comments-25", amount: 25, price: 9.99, originalPrice: 19.98 },
      { id: "comments-50", amount: 50, price: 17.99, originalPrice: 35.98 },
      { id: "comments-100", amount: 100, price: 29.99, originalPrice: 59.98 },
    ],
  },
  tiktok: {
    followers: tiktokFollowersPackages,
    likes: [
      { id: "likes-500", amount: 500, price: 1.99, originalPrice: 3.98 },
      { id: "likes-1000", amount: 1000, price: 3.49, originalPrice: 6.98 },
      { id: "likes-2500", amount: 2500, price: 6.99, originalPrice: 13.98 },
      { id: "likes-5000", amount: 5000, price: 12.99, originalPrice: 25.98 },
      { id: "likes-10000", amount: 10000, price: 22.99, originalPrice: 45.98 },
    ],
    views: [
      { id: "views-1000", amount: 1000, price: 0.99, originalPrice: 1.98 },
      { id: "views-5000", amount: 5000, price: 2.99, originalPrice: 5.98 },
      { id: "views-10000", amount: 10000, price: 4.99, originalPrice: 9.98 },
      { id: "views-50000", amount: 50000, price: 14.99, originalPrice: 29.98 },
      { id: "views-100000", amount: 100000, price: 24.99, originalPrice: 49.98 },
    ],
    shares: [
      { id: "shares-100", amount: 100, price: 3.99, originalPrice: 7.98 },
      { id: "shares-250", amount: 250, price: 7.99, originalPrice: 15.98 },
      { id: "shares-500", amount: 500, price: 14.99, originalPrice: 29.98 },
      { id: "shares-1000", amount: 1000, price: 24.99, originalPrice: 49.98 },
    ],
  },
  youtube: {
    subscribers: youtubeSubscribersPackages,
    views: [
      { id: "views-1000", amount: 1000, price: 3.99, originalPrice: 7.98 },
      { id: "views-5000", amount: 5000, price: 12.99, originalPrice: 25.98 },
      { id: "views-10000", amount: 10000, price: 22.99, originalPrice: 45.98 },
      { id: "views-50000", amount: 50000, price: 79.99, originalPrice: 159.98 },
    ],
    likes: [
      { id: "likes-500", amount: 500, price: 4.99, originalPrice: 9.98 },
      { id: "likes-1000", amount: 1000, price: 8.99, originalPrice: 17.98 },
      { id: "likes-2500", amount: 2500, price: 19.99, originalPrice: 39.98 },
      { id: "likes-5000", amount: 5000, price: 34.99, originalPrice: 69.98 },
    ],
    watchTime: [
      { id: "watch-1000", amount: 1000, price: 19.99, originalPrice: 39.98, unit: "hours" },
      { id: "watch-4000", amount: 4000, price: 69.99, originalPrice: 139.98, unit: "hours" },
    ],
  },
}

export const platforms = [
  { id: "instagram", name: "Instagram", icon: "Instagram", color: "from-pink-500 via-purple-500 to-orange-500" },
  { id: "tiktok", name: "TikTok", icon: "Music2", color: "from-cyan-400 via-black to-pink-500" },
  { id: "youtube", name: "YouTube", icon: "Youtube", color: "from-red-600 to-red-500" },
]

export const testimonials = [
  {
    id: 1,
    name: "María García",
    avatar: "/woman-profile.png",
    rating: 5,
    comment: "Increíble servicio! Mis seguidores llegaron en menos de 24 horas. 100% recomendado.",
    platform: "Instagram",
  },
  {
    id: 2,
    name: "Carlos Mendoza",
    avatar: "/man-profile.png",
    rating: 5,
    comment: "El mejor servicio de SMM que he probado. Seguidores reales y soporte excelente.",
    platform: "TikTok",
  },
  {
    id: 3,
    name: "Ana Rodríguez",
    avatar: "/young-woman-profile.png",
    rating: 5,
    comment: "Mi canal de YouTube creció increíblemente rápido. Volveré a comprar.",
    platform: "YouTube",
  },
]

export const faqs = [
  {
    question: "¿Son seguidores reales?",
    answer:
      "Sí, todos nuestros seguidores son cuentas reales con actividad. No usamos bots ni cuentas falsas que puedan perjudicar tu cuenta.",
  },
  {
    question: "¿Cuánto tarda la entrega?",
    answer:
      "El tiempo de entrega varía según el paquete seleccionado. Generalmente entre 24 horas y 10 días, dependiendo de la cantidad.",
  },
  {
    question: "¿Es seguro para mi cuenta?",
    answer:
      "Absolutamente. Usamos métodos seguros y graduales de entrega que respetan las políticas de las plataformas. Tu cuenta está 100% protegida.",
  },
  {
    question: "¿Ofrecen garantía?",
    answer:
      "Sí, todos nuestros paquetes incluyen garantía de reposición. Si pierdes seguidores durante el período de garantía, los reponemos gratis.",
  },
  {
    question: "¿Qué métodos de pago aceptan?",
    answer: "Aceptamos tarjetas de crédito/débito, PayPal, transferencias bancarias y criptomonedas para tu comodidad.",
  },
  {
    question: "¿Necesitan mi contraseña?",
    answer: "No, nunca. Solo necesitamos tu nombre de usuario público. Tu seguridad es nuestra prioridad.",
  },
]
