export const instagramFollowersPackages = [
  {
    id: "starter",
    name: "STARTER",
    followers: 1000,
    price: 15,
    currency: "USD",
    delivery: "24-48h",
    quality: "Seguidores reales",
    guarantee: "30 días",
    support: "Email",
    popular: false,
    bestValue: false,
  },
  {
    id: "viral",
    name: "VIRAL",
    followers: 5000,
    price: 65,
    currency: "USD",
    delivery: "48-72h",
    quality: "Seguidores de calidad",
    guarantee: "60 días",
    support: "Prioritario",
    popular: true,
    bestValue: false,
  },
  {
    id: "pro",
    name: "PRO",
    followers: 10000,
    price: 120,
    currency: "USD",
    delivery: "3-5 días",
    quality: "Seguidores premium",
    guarantee: "90 días",
    support: "Prioritario",
    popular: false,
    bestValue: true,
  },
  {
    id: "platinum",
    name: "PLATINUM",
    followers: 25000,
    price: 280,
    currency: "USD",
    delivery: "5-7 días",
    quality: "Seguidores elite",
    guarantee: "120 días",
    support: "24/7 Dedicado",
    popular: false,
    bestValue: false,
  },
  {
    id: "supremo",
    name: "SUPREMO",
    followers: 50000,
    price: 500,
    currency: "USD",
    delivery: "7-10 días",
    quality: "Seguidores VIP",
    guarantee: "Ilimitada",
    support: "24/7 VIP",
    popular: false,
    bestValue: false,
  },
]

export const tiktokFollowersPackages = [
  {
    id: "starter",
    name: "STARTER",
    followers: 1000,
    price: 12,
    currency: "USD",
    delivery: "24-48h",
    quality: "Seguidores reales",
    guarantee: "30 días",
    support: "Email",
    popular: false,
    bestValue: false,
  },
  {
    id: "viral",
    name: "VIRAL",
    followers: 5000,
    price: 55,
    currency: "USD",
    delivery: "48-72h",
    quality: "Seguidores de calidad",
    guarantee: "60 días",
    support: "Prioritario",
    popular: true,
    bestValue: false,
  },
  {
    id: "pro",
    name: "PRO",
    followers: 10000,
    price: 100,
    currency: "USD",
    delivery: "3-5 días",
    quality: "Seguidores premium",
    guarantee: "90 días",
    support: "Prioritario",
    popular: false,
    bestValue: true,
  },
  {
    id: "platinum",
    name: "PLATINUM",
    followers: 25000,
    price: 230,
    currency: "USD",
    delivery: "5-7 días",
    quality: "Seguidores elite",
    guarantee: "120 días",
    support: "24/7 Dedicado",
    popular: false,
    bestValue: false,
  },
  {
    id: "supremo",
    name: "SUPREMO",
    followers: 50000,
    price: 420,
    currency: "USD",
    delivery: "7-10 días",
    quality: "Seguidores VIP",
    guarantee: "Ilimitada",
    support: "24/7 VIP",
    popular: false,
    bestValue: false,
  },
]

export const youtubeSubscribersPackages = [
  {
    id: "starter",
    name: "STARTER",
    followers: 500,
    price: 20,
    currency: "USD",
    delivery: "24-48h",
    quality: "Suscriptores reales",
    guarantee: "30 días",
    support: "Email",
    popular: false,
    bestValue: false,
  },
  {
    id: "viral",
    name: "VIRAL",
    followers: 2500,
    price: 85,
    currency: "USD",
    delivery: "48-72h",
    quality: "Suscriptores de calidad",
    guarantee: "60 días",
    support: "Prioritario",
    popular: true,
    bestValue: false,
  },
  {
    id: "pro",
    name: "PRO",
    followers: 5000,
    price: 150,
    currency: "USD",
    delivery: "3-5 días",
    quality: "Suscriptores premium",
    guarantee: "90 días",
    support: "Prioritario",
    popular: false,
    bestValue: true,
  },
  {
    id: "platinum",
    name: "PLATINUM",
    followers: 10000,
    price: 280,
    currency: "USD",
    delivery: "5-7 días",
    quality: "Suscriptores elite",
    guarantee: "120 días",
    support: "24/7 Dedicado",
    popular: false,
    bestValue: false,
  },
  {
    id: "supremo",
    name: "SUPREMO",
    followers: 25000,
    price: 600,
    currency: "USD",
    delivery: "7-10 días",
    quality: "Suscriptores VIP",
    guarantee: "Ilimitada",
    support: "24/7 VIP",
    popular: false,
    bestValue: false,
  },
]

export const platforms = [
  { id: "instagram", name: "Instagram", icon: "Instagram" },
  { id: "tiktok", name: "TikTok", icon: "Music2" },
  { id: "youtube", name: "YouTube", icon: "Youtube" },
]

export const testimonials = [
  {
    id: 1,
    name: "María García",
    avatar: "/woman-profile.png",
    rating: 5,
    comment: "Increíble servicio! Mis seguidores llegaron en menos de 24 horas. 100% recomendado.",
    platform: "Instagram",
  },
  {
    id: 2,
    name: "Carlos Mendoza",
    avatar: "/man-profile.png",
    rating: 5,
    comment: "El mejor servicio de SMM que he probado. Seguidores reales y soporte excelente.",
    platform: "TikTok",
  },
  {
    id: 3,
    name: "Ana Rodríguez",
    avatar: "/young-woman-profile.png",
    rating: 5,
    comment: "Mi canal de YouTube creció increíblemente rápido. Volveré a comprar.",
    platform: "YouTube",
  },
]

export const faqs = [
  {
    question: "¿Son seguidores reales?",
    answer:
      "Sí, todos nuestros seguidores son cuentas reales con actividad. No usamos bots ni cuentas falsas que puedan perjudicar tu cuenta.",
  },
  {
    question: "¿Cuánto tarda la entrega?",
    answer:
      "El tiempo de entrega varía según el paquete seleccionado. Generalmente entre 24 horas y 10 días, dependiendo de la cantidad.",
  },
  {
    question: "¿Es seguro para mi cuenta?",
    answer:
      "Absolutamente. Usamos métodos seguros y graduales de entrega que respetan las políticas de las plataformas. Tu cuenta está 100% protegida.",
  },
  {
    question: "¿Ofrecen garantía?",
    answer:
      "Sí, todos nuestros paquetes incluyen garantía de reposición. Si pierdes seguidores durante el período de garantía, los reponemos gratis.",
  },
  {
    question: "¿Qué métodos de pago aceptan?",
    answer: "Aceptamos tarjetas de crédito/débito, PayPal, transferencias bancarias y criptomonedas para tu comodidad.",
  },
  {
    question: "¿Necesitan mi contraseña?",
    answer: "No, nunca. Solo necesitamos tu nombre de usuario público. Tu seguridad es nuestra prioridad.",
  },
]
